name       : perl-test-without-module
version    : '0.21'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/C/CO/CORION/Test-Without-Module-0.21.tar.gz : 3cdeafadac4853ebeafe689346d555da5dfa3cfa9d4c84e3e5e7bfee50beec46
homepage   : https://metacpan.org/pod/Test::Without::Module
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Without::Module - Test fallback behaviour in absence of modules
description: |
    This module allows you to deliberately hide modules from a program even though they are installed. This is mostly useful for testing modules that have a fallback when a certain dependency module is not installed.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
